version: 0.1.0.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: uZr+CJU4Pl/9ySY0sDQh62xBZaqlEQB7s6fZEmG58InhSjbwslq6mKIWxd1Q55TO

platform: Any CPU

before_build:
  - nuget restore GestionDroits.sln

build:
  project: GestionDroits.sln

after_test:
  - cmd: .\after_test.cmd

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Slack
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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